image: gradle:6.8.3-jdk11

stages:
  - build
  - javadoc
  - sonarqube&test
  - docerize



build:
  stage: build
  tags:
    - sonar
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 week

sonarqube:
  stage: sonarqube&test
  tags:
    - sonar
  script:
    - ./gradlew test
    - ./gradlew sonarqube -Dsonar.projectKey=VVPSTA -Dsonar.host.url=http://localhost:9000 -Dsonar.login=08cf5e193cd203639be96dfc2122621dfeb40493
  artifacts:
    when: on_failure
    paths:
      - ./*
    expire_in: 1 week

test:
  stage: javadoc
  tags:
    - sonar
  script:
    - ./gradlew javadoc
  artifacts:
    paths:
      - build/docs/javadoc/de
    expire_in: 1 week

build-docker:
  stage: docerize
  tags:
    - sonar
  script:
    - ./gradlew build
    - docker build -t inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander
  only:
    refs:
      - master
