image: gradle:6.8.3-jdk11

stages:
  - build
  - javadoc
  - sonarqube&test
  - docerize



build:
  stage: build
  tags:
    - sonar
  script:
    - ./gradlew server:builde
    - ./gradlew sensor:build
  artifacts:
    paths:
      - ./build/libs/server-1.0-SNAPSHOT.jar
      - ./build/libs/sensor-1.0-SNAPSHOT-all.jar
    expire_in: 1 week

sonarqube:
  stage: sonarqube&test
  tags:
    - sonar
  script:
    - ./gradlew test
    - ./gradlew sonarqube
  artifacts:
    when: on_failure
    paths:
      - ./*
    expire_in: 1 week

javadoc:
  stage: javadoc
  tags:
    - sonar
  script:
    - ./gradlew server:javadoc
  artifacts:
    paths:
      - build/docs/javadoc/de
    expire_in: 1 week

build-docker:
  stage: docerize
  tags:
    - sonar
  script:
    - ./gradlew server:build
    - cd ./server
    - docker build -t inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/server .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/server
    - cd ../
    - ./gradlew sensor:build
    - cd ./sensor
    - docker build -t inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/sensor .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/sensor
  only:
    refs:
      - master
      - developement
