image: gradle:6.8.3-jdk11

stages:
  - build
  - test

build:
  stage: build
  image: gradle:6.8.3-jdk11
  script: gradle build
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script: gradle check
