image: gradle:6.8.3-jdk11

stages:
  - build
  - javadoc
  - sonarqube&test
  - docerize



build:
  stage: build
  tags:
    - sonar
  script:
    - ./gradlew server:builde
    - ./gradlew sensor:build
    - ./gradlew actor:build
  artifacts:
    paths:
      - ./server/build/libs/*.jar
      - ./actor/build/libs/*.jar
      - ./sensor/build/libs/*.jar
    expire_in: 1 week

sonarqube:
  stage: sonarqube&test
  needs:
    - job: build
  tags:
    - sonar
  script:
    - ./gradlew test
    - ./gradlew sonarqube
  artifacts:
    when: on_failure
    paths:
      - ./*
    expire_in: 1 week

javadoc:
  stage: javadoc
  needs:
    - job: build
  tags:
    - sonar
  script:
    - ./gradlew server:javadoc
    - ./gradlew sensor:javadoc
    - ./gradlew actor:javadoc
  artifacts:
    paths:
      - ./server/build/docs/javadoc/de
      - ./sensor/build/docs/javadoc/de
      - ./actor/build/docs/javadoc/de
    expire_in: 1 week

build-docker:
  stage: docerize
  tags:
    - sonar
  script:
    - ./gradlew server:build
    - cd ./server
    - docker build -t inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/server .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/server
    - cd ../
    - ./gradlew sensor:build
    - cd ./sensor
    - docker build -t inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/sensor .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/sensor
    - cd ../
    - ./gradlew actor:build
    - cd ./actor
    - docker build -t inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/actor .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker push inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/actor
  only:
    refs:
      - master
      - developement
