image: gradle:6.8.3-jdk11

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - build

build:
  stage: build
  image: gradle:6.8.3-jdk11
  script: 
    - gradle assemble && gradle jar
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ls -la build/ 
    - gradle check
