image: gradle:6.8.3-jdk11

stages:
  #- build
  #- test
  #- sonarqube
  - docerize


docker-build:
  stage: docerize
  tags:
    - sonar
  script:
    - docker build --pull -t asbeck .
    - docker push asbeck