image: gradle:6.8.3-jdk11

stages:
  - test
  - build
  - sonarqube



build:
  stage: build
  image: gradle:6.8.3-jdk11
  script: 
    - gradle assemble && gradle jar
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 week

sonarqube:
  stage: sonarqube
  tags:
    - sonar
  script:
    - ./gradlew test
    - ./gradlew sonarqube -Dsonar.projectKey=VVPSTA -Dsonar.host.url=http://localhost:9000 -Dsonar.login=08cf5e193cd203639be96dfc2122621dfeb40493

test:
  stage: test
  script:
    - ls -la
    - gradle test
    - cat ./logs/log.log
  artifacts:
    when: on_failure
    paths:
      - ./*
    expire_in: 1 week
