version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: SmartHomeService
      MYSQL_USER: Alex
      MYSQL_PASSWORD: 1234
    networks:
      - mysqlconnector
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 10s
      timeout: 2s
      retries: 10

  service:
    image: inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/server:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LOG_LEVEL=info
      - SqlUrl=db
    ports:
      - 9000:9000
    networks:
      - mysqlconnector

  sensor1:
    image: ss21vvexercise02/demosensor:latest
    restart: always
    depends_on:
      - service
    environment:
      - SensorId=1
      - SmartHomeServiceRegistrationURL=http://service:9000/v1/sensors
      - SmartHomeServicePublishURL=http://service:9000/v1/sensors
    networks:
      - mysqlconnector

  sensor2:
    image: inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/sensor:latest
    restart: always
    depends_on:
      - service
    environment:
      - SensorId=2
      - ServerRegistrationURL=http://service:9000/v1/sensors
      - ServerPublishURL=http://service:9000/v1/sensors
    networks:
      - mysqlconnector

  demoaktor:
    image:  ss21vvexercise02/demoaktor:latest
    container_name: vvss21-demoaktor-livingRoom
    restart: always
    ports:
      - 9212:80
      - 4502:443
    environment:
      - AktorId=1
      - SmartHomeServiceRegistrationURL=http://service:9000/v1/aktors
    networks:
      - mysqlconnector

  actor:
    image: inf-docker.fh-rosenheim.de/vv-inf-sose21/asbeckalexander/actor:latest
    restart: always
    depends_on:
      - service
    environment:
      - ActorId=2
      - ServerRegistrationURL=http://service:9000/v1/actors
    networks:
      - mysqlconnector

networks:
  mysqlconnector: